version: '3'

services:

  app:
      build:
        context: ./node
        dockerfile: Dockerfile.prod
      container_name: app
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s ./runApp.sh
      networks:
        - node-network
      volumes:
        - ./node:/usr/src/app
      tty: true
      ports:
        - "3000:3000"
      depends_on:
        - db
    
  nginx:
      image: nginx
      build:
        context: ./nginx
        dockerfile: Dockerfile.prod
      container_name: nginx  
      networks:
        - node-network
      volumes: 
        - ./nginx:/usr/share/nginx/html
      ports:
        - 8080:80 #o acesso à porta 8080 na máquina acessa a porta 80 do container
      depends_on:
        - app

  db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_USER=luksave
        - MYSQL_ROOT_PASSWORD=123
      networks:
        - node-network


networks:
    node-network:
      driver: bridge